[project]
name = "ariel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "JMDM", email = "jmo.880@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "mujoco>=3.3.2",
    "mypy>=1.15.0",
    "numpy>=2.2.5",
    "rich>=14.0.0",
    "ruff>=0.11.7",
    "trimesh[easy]>=4.6.8",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
