[project]
name = "ariel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "JMDM", email = "jmo.880@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "mujoco>=3.3.4",
    "mypy>=1.16.1",
    "networkx>=3.5",
    "numpy>=2.3.1",
    "numpy-quaternion>=2024.0.10",
    "opencv-python>=4.11.0.86",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "rich>=14.0.0",
    "ruff>=0.12.2",
    "trimesh[easy]>=4.7.0",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
